### ISSUE TITLE
Erro no campo taxa do Cadastro de taxas

### ISSUE THREAD

**Issue by danieldestro** [diogocorreiasan/escalaDeArbitros#1]
Cadastro de Taxas... o campo do valor nao eh facil de usar.... se coloca "50" e salva ele da msg de erro.. ele froca voce digita 5000 pra ele formatar pra "50.00".... tem que ser mais simples.

**Comment by diogocorreiasan** [comment]
Fechado

**Comment by danieldestro** [comment]
ver issue #16
