### ISSUE TITLE
Cadastro Jogo não limpa campos

### ISSUE THREAD

**Issue by danieldestro** [diogocorreiasan/escalaDeArbitros#20]
Edite algum jogo cadastrado.
Clique no botão de cancelar.
Clique no botão "Novo Jogo".

Esperado: campos vazios para digitação.
Erro: campos contém os dados do último jogo editado.

**Comment by diogocorreiasan** [comment]
Feito

**Comment by danieldestro** [comment]
Foi arrumado em qual branch?

**Comment by danieldestro** [comment]
branch: confirmacao_de_senha
Testado e OK!
